import type { NextPage } from "next";
import Head from "next/head";
import { CharityMarketDetailModule } from "../modules/CharityMarketDetailModule/charityMarketDetailModule";

const CharityMarketDetail = () => {
    return (
        <>
            <Head>
                <title>PIF Charity | Charity Market Details</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <CharityMarketDetailModule />
        </>
    );
};

export default CharityMarketDetail;