import type { NextPage } from "next";
import Head from "next/head";
import LandingModule from "../modules/LandingModule/LandingModule";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Atlanten | Landing-page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingModule />
    </div>
  );
};

export default Home;
